name: Email Step Demo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 24f2002824@ds.study.iitm.ac.in
        run: echo "Hello, world!"
